### ISSUE TITLE
Add support for multiple AWS accounts

### ISSUE THREAD

**Issue by berniedurfee-ge** [envato/stack_master#109]
When using multiple accounts, it would help to be able to specify an AWS credentials profile in the stack_master.yml file for a particular environment.

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles

I think this might mean that instead of a region being the only attribute for where to 'run' the stack, you'd need multiple attributes to describe the 'environment' in which to run the stack. At least the region and the credentials profile to use.

Example

```
environments:
  production-us:
    region: us-east-1
    profile: prod_profile
  production-eu:
    region: eu-west-1
    profile: prod_profile
  development-us:
    region: us-east-1
    profile: dev_profile
stacks:
  production-us:
    my_stack:
      template: my_prod_stack.cf.json
  production-eu:
    my_stack:
      template: my_prod_stack.cf.json
  development-us:
    my_stack:
      template: my_dev_stack.cf.json
```

**Comment by nemski** [comment]
I like this idea, but I wonder how we could allow integration to multiple key storage tools. the AWS CLI mechanism of storing keys un-encrypted on disk is not ideal. I use aws-vault for instance, but there are plenty of other tools.

Still, supporting the CLI would be a good first cut.

**Comment by stevehodgkiss** [comment]
I like the concept of environments (to replace region_aliases). It would be nice if StackMaster knew how to get _default_ credentials, but also allow them to be overridden if needed. There are cases where you would want to use a different role in order to apply a change, such as delete an RDS database if the default/usual role doesn't allow that. Teams would need to use the same AWS Vault profile name for this to work well.

One option is to introduce the concept of credential providers, but allow those to be overridden or ignored if credentials already exist in the environment.

```
environments:
  production-us-east-1:
    region: us-east-1
    credentials:
      profile: myteam-production
      # or
      aws-vault: myteam-production
      # or
      cmd: aws-keys env myteam-production
```

We'd need some kind of output at the beginning of a SM run to declare which credentials are being used, ENV, or the defined default credentials.

**Comment by patrobinson** [comment]
I don't think stack master should _source_ the credentials for you, that should be the job of the credentials provider (or some wrapper code). I understand aws profiles don't do this, but that's why I prefer aws-vault.

What I would like is some indication as to what account the stack should live in, so if I blindly look at the stack_master.yml file I can easily dissect production from staging, which may or may not be in the same region.

**Comment by flyinbutrs** [comment]
I have a patch in the works that implements region_aliases more like environments, but I was really just changing region_aliases to be able to have mutliple aliases for the same region. Is that viable, or would you (the maintainers) prefer to have environments as a separate config key that behaves one way while preserving the region_aliases as they are now. 

Also, WRT to environments, one other thing I was working on (though as an optional parameter) to go with this was to have the created stacks prepend the region_alias / environment name. So the config below would create a stack called "prod-app" instead of just app.

````
stacks:
  prod:
    app:
      template: app.json
````
