### ISSUE TITLE
Support for stack tags

### ISSUE THREAD

**Issue by berniedurfee-ge** [envato/stack_master#112]
Default tags can be set for all stacks or for regions, but it would be good to allow tags at the stack level. For example, if I have a stack that builds a particular tier or service, I want to add a tag: "service":"data-collector"

```
region_aliases:
  production: us-east-1
  staging: ap-southeast-2
stack_defaults:
  tags:
    application: my-awesome-app
region_defaults:
  us-east-1:
    secret_file: production.yml.gpg
    tags:
      environment: production
    notification_arns:
      - test_arn
  ap-southeast-2:
    secret_file: staging.yml.gpg
    tags:
      environment: staging
stacks:
  production:
    myapp-vpc:
      template: myapp_vpc.rb
***
      tags:
            service: data-collector
***
```
