### ISSUE TITLE
Feature Suggestion - Adding support for stack include files in Stack_Master.yml 

### ISSUE THREAD

**Issue by jamesbjackson** [envato/stack_master#153]
We have large amounts of Stacks and a lot of them have common templates and names across our infrastructure so was wondering if I looked at a way to dynamically add include blocks to the yml file so when Stack_Master read the file it would dynamically inject the referenced files.

My current thought is something like this inside a region block .. Where like we have a parameters directory we can also now have a stacks directory and we have the same override system as parameters. As currently we have to use multiple stack_master.yml files to have this behaviour and it be great to be able to have our stack_master really clean and allow us to break up our stacks into nice reusable components and reducing duplications.

```yaml
--- 
stacks: 
  eu-west-1: 
    includes: 
      - s3_buckets.yml
      - virtual_private_cloud.yml
      - private_subnets.yml
      - public_subnets.yml
      - security_groups.yml
      - emr_cluster.yml
      - ec2_instances.yml
  us-east-1: 
    includes: 
      - s3_buckets.yml
      - virtual_private_cloud.yml
      - private_subnets.yml
      - public_subnets.yml
      - security_groups.yml
      - emr_cluster.yml
      - ec2_instances.yml
  us-west-2: 
    includes: 
      - s3_buckets.yml
      - virtual_private_cloud.yml
      - private_subnets.yml
      - public_subnets.yml
      - security_groups.yml
      - emr_cluster.yml
      - ec2_instances.yml		
```

Any suggestion about how best to build this feature as happy to do the coding to get this done and submit a PR. Just wondered what people thought of the best way to get this included..
