### ISSUE TITLE
Add support for pre/post-apply/delete actions

### ISSUE THREAD

**Issue by samuelsuarezsanchez** [envato/stack_master#163]
It would be great if stacks could be setup so certain actions (or hooks) could run before and after applying and deleting them.

In my head, indicating the actions would be done in the `stack_master.yml` itself. Something like:

```
stacks:
  us-east-1:
    my-s3-bucket:
      pre_apply: delete-if-exists.rb
      post_apply: print-outputs.rb
      pre_delete: delete-bucket-contents.rb
      post_delete: notify-admins.rb
```

* On a very basic version, we would be talking about executable scripts in any language that would receive as parameters:

| Action | Parameters |
| --- | --- |
| `pre_apply` | The compiled CloudFormation JSON template and parameters. |
| `post_apply` | The compiled CloudFormation JSON template, parameters and output values. |
| `pre_delete` | The compiled CloudFormation JSON template to be deleted, parameters and output values. |
| `post_delete` | Same as `pre_delete`. |

* If the script returns zero, then `stack_master` would continue execution. Any non-zero return code would interrupt the execution.

* Actions would be located under an `actions` directory at the same level as `parameters`, `templates`, etc.
