### ISSUE TITLE
apply does nothing(must ctrl-c) when using region aliases

### ISSUE THREAD

**Issue by jonjitsu** [envato/stack_master#192]
The following stack_master.yml `apply`s fine, where s3.yaml creates a simple s3 bucket
```yaml
stacks:
  us-east-1:
    s3:
      template: s3.yaml
      tags:
        environment: dev
```

when I try to use aliases:
```yaml
region_aliases:
  dev: us-east-1
stacks:
  dev:
    s3:
      template: s3.yaml
      tags:
        environment: dev
```
stack_master apply just sits there with the message:
Executing apply on s3 in dev 

no errors or stack traces. I have left it run for minutes to see if I can get some hint of what's wrong.
I have tried with ruby 2.4.0/2.3.4/2.2.*. I even tried inside a docker container to try to isolate my environment.
