### ISSUE TITLE
template: value does not honour absolute paths

### ISSUE THREAD

**Issue by et304383** [envato/stack_master#207]
If I do something like this:

```
stack:
  us-east-1:
    stack-name:
      template: /absolute/path/to/template.yml
```

It will take the current directory (of stack_master.yml) and append `/absolute/path/to/template.yml`
