### ISSUE TITLE
Proposal: Templates from gems

### ISSUE THREAD

**Issue by mipearson** [envato/stack_master#261]
(unlike the other proposals, this one is for stack_master 1, not 2)

I want to be able to ship CFN templates (`.yml`) as part of a private gem for others to use. 

The workflow would be:

  1. Add to `Gemfile`, lock to patch version
  1. Reference template(s) in gem in `stack_master.yml` as normal
  1. Update incrementally & carefully if desired

`stack_master.yml` would look like:

```yaml
stacks:
  us-east-1:
    my-vpc:
      gem-template: mygem/vpc.yml
```

`mygem` would be discovered and an error displayed if the gem is not found or the template does not exist. `mygem` would only consist of a mostly-empty `mygem.gemspec` and a `templates` directory.

Optionally other stack_master compiled formats (eg sparkleformation, cfndsl) could be supported.

This would also allow people wishing to modify / contribute back to the templates in the gem to vendor it locally using the existing Bundler mechanisms for [working on code locally](https://ryanbigg.com/2013/08/bundler-local-paths)

**Comment by rbayerl** [comment]
I would rather see it as `mygem:vpc.yml` rather than taking over the idea of a local path. Other than that no opinion. Another option would be something like:
```
stacks:
  us-east-1:
    my-vpc:
      gem-template:
        mygem: vpc.yml
```
